# Remote backend configuration for state migration
# Use with: terraform init -migrate-state -backend-config=backend-remote.hcl
#
# IMPORTANT: This file will be auto-generated by generate-credentials.sh
# with the actual MinIO credentials. Do not edit manually.
#
# Usage:
# 1. source .minio-credentials
# 2. ./generate-backend-config.sh
# 3. terraform init -migrate-state -backend-config=backend-remote.hcl

bucket                      = "terraform-state"
key                        = "bootstrap/terraform.tfstate"
endpoint                   = "http://bootstrap-minio.bootstrap.svc.cluster.local:9000"
region                     = "us-east-1"
access_key                 = "PLACEHOLDER_ACCESS_KEY"
secret_key                 = "PLACEHOLDER_SECRET_KEY"
skip_credentials_validation = true
skip_metadata_api_check     = true
skip_region_validation      = true
force_path_style           = true

