# Bootstrap State Variables

variable "node_count" {
  description = "Number of nodes in the cluster"
  type        = number
  default     = 1
}

variable "minio_storage_size" {
  description = "Storage size for MinIO"
  type        = string
  default     = "10Gi"
}

variable "postgresql_storage_size" {
  description = "Storage size for PostgreSQL"
  type        = string
  default     = "8Gi"
}

variable "environment" {
  description = "Environment phase (homelab or business)"
  type        = string
  default     = "homelab"

  validation {
    condition     = contains(["homelab", "business"], var.environment)
    error_message = "Environment must be either 'homelab' or 'business'."
  }
}

variable "minio_access_key" {
  description = "MinIO access key (generated by bootstrap script)"
  type        = string
  sensitive   = true
}

variable "minio_secret_key" {
  description = "MinIO secret key (generated by bootstrap script)"
  type        = string
  sensitive   = true
}