# Bootstrap State Variables

variable "node_count" {
  description = "Number of nodes in the cluster"
  type        = number
  default     = 1
}

variable "minio_storage_size" {
  description = "Storage size for MinIO"
  type        = string
  default     = "10Gi"
}

variable "postgresql_storage_size" {
  description = "Storage size for PostgreSQL"
  type        = string
  default     = "8Gi"
}

variable "resource_tier" {
  description = "Resource tier for CPU/memory/storage sizing: small, medium, or large"
  type        = string
  default     = "small"

  validation {
    condition     = contains(["small", "medium", "large"], var.resource_tier)
    error_message = "Resource tier must be: small, medium, or large."
  }
}

variable "minio_root_user" {
  description = "MinIO root user (generated by bootstrap script)"
  type        = string
  sensitive   = true
}

variable "minio_root_password" {
  description = "MinIO root password (generated by bootstrap script)"
  type        = string
  sensitive   = true
}

variable "postgres_password" {
  description = "PostgreSQL password (generated by bootstrap script)"
  type        = string
  sensitive   = true
}